# Generated by Django 4.1.4 on 2023-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_page_pagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
