# Generated by Django 4.1.4 on 2023-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_image_description_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
