# Generated by Django 4.1.4 on 2023-05-25 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_pagecontent_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('gr', 'German'), ('tr', 'Turkish')], max_length=2)),
                ('translated_text', models.TextField()),
                ('page_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.pagecontent')),
            ],
            options={
                'unique_together': {('language', 'page_content')},
            },
        ),
    ]
