# Generated by Django 4.2.1 on 2023-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_translatedpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='language',
            field=models.CharField(choices=[('tr', 'Turkish'), ('en', 'English'), ('de', 'German')], default='tr', max_length=2),
        ),
        migrations.AlterField(
            model_name='translatedpagecontent',
            name='language',
            field=models.CharField(choices=[('tr', 'Turkish'), ('en', 'English'), ('de', 'German')], max_length=2),
        ),
    ]
